# Prerequisites

In [88]:
import os
os.chdir('/Users/bamjy99/Desktop/experiment')
os.getcwd()

'/Users/bamjy99/Desktop/experiment'

In [89]:
!pip3 install pyreadstat
!pip3 install scikit-learn
!pip3 install openai
!pip3 install transformers
!pip3 install tqdm
!pip3 install matplotlib

Requirement already satisfied: pyreadstat in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.2.8)
Requirement already satisfied: pandas>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pyreadstat) (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2.0->pyreadstat) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/bamjy99/Library/Python/3.13/lib/python/site-packages (from pandas>=1.2.0->pyreadstat) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2.0->pyreadstat) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2.0->pyreadstat) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/bamjy99/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: pip3 install --upgrade pip
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (2.2.4)
Requirement already satisfied: scipy>=1.6.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: pip3 install --upgrade pip
Requirement already satisfied: openai in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.87.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openai) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openai) (2.11.7)
Requirement already satisfied: sniffio in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openai) (4.13.2)
Requirement already satisfied: idna>=2.8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from httpx<1,>=0.23.0->openai) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: pip3 install --upgrade pip
Requirement already satisfied: transformers in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (4.51.3)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers) (0.30.2)
Requirement already satisfied: numpy>=1.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers) (2.2.4)
Requirement already satisfied: packaging>=20.0 in /Users/bamjy99/Library/Python/3.13/lib/python/site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->transformers) (2025.1.31)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: pip3 install --upgrade pip
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (4.67.1)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: pip3 install --upgrade pip
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (2.2.4)
Requirement already satisfied: packaging>=20.0 in /Users/bamjy99/Library/Python/3.13/lib/python/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/bamjy99/Library/Python/3.13/lib/python/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/bamjy99/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: pip3 install --upgrade pip

In [90]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import pyreadstat

from tqdm import tqdm
from openai import OpenAI
from transformers import pipeline
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [91]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Question Data

In [92]:
qdf = pd.read_csv('/Users/bamjy99/Desktop/experiment/question.csv')
qdf.head()

,Tag,Question,Specific
0,Demographic,당신의 아버지의 나이는? (a)30대 이하 (b)40대 (c)50대이상,NaN
1,Demographic,당신의 어머니의 나이는? (a)30대 이하 (b)40대 (c)50대이상,NaN
2,Demographic,당신의 아버지는 학교를 어디까지 다니셨나요? (a)초등학교 졸업 또는 중퇴 (b)중학교 졸업 또는 중퇴 (c)고등학교 졸업 또는 중퇴 (d)대학교 졸업 또는 중퇴 (e)대학원 이상 (f)아버지 안계심,NaN
3,Demographic,당신의 어머니는 학교를 어디까지 다니셨나요? (a)초등학교 졸업 또는 중퇴 (b)중학교 졸업 또는 중퇴 (c)고등학교 졸업 또는 중퇴 (d)대학교 졸업 또는 중퇴 (e)대학원 이상 (f)어머니 안계심,NaN
4,Demographic,"당신의 아버지의 직업은 무엇인가요? (a)전문직 예를 들어 의사, 교사 등 (b)사무직 예를 들어 공무원, 회사원 등 (c)공장 및 건설노동자 (d)판매/ 서비스직 예를 들어 상점이나 식당 경영, 혹은 종업원 등 (e)농어업 (f)직업이 없음 (g)아버지 안계심 (h)기타",NaN

In [93]:
def replace_bracket_text(row):
    if pd.notnull(row['Specific']):
        return re.sub(r'\[.*?\]', str(row['Specific']), row['Question'])
    else:
        return row['Question']

qdf['Question'] = qdf.apply(replace_bracket_text, axis=1)
qdf = qdf.drop(columns=['Specific']) #Specific 열 삭제

In [94]:
qdf.tail()

,Tag,Question
56,Depression,당신은 당신 스스로가 나는 누군가를 때리거나 해치고 싶은 충동이 생길 때가 있다고 생각하시나요? (a)전혀 그렇지 않다 (b)별로 그렇지 않다 (c)그저 그렇다 (d)대체로 그렇다 (e)매우 그렇다
57,Multiculture,당신은 자신을 누구라고 생각하나요? (a)나는 한국인이다 (b)나는 외국인이다 (c)나는 한국인과 외국인 모두에 해당된다 (d)나는 한국인도 아니고 외국인도 아니다
58,Multiculture,당신의 외국인 부모님은 한국말을 잘 하시나요? (a)전혀 그렇지 않다 (b)별로 그렇지 않다 (c)그저 그렇다 (d)대체로 그렇다 (e)매우 그렇다
59,Multiculture,당신은 한국말을 잘 하나요? (a)전혀 못한다 (b)조금 한다 (c)어느정도 잘한다 (d)매우 잘한다
60,Multiculture,당신은 학교나 동네에서 다문화가정 자녀라는 이유로 놀림이나 차별을 받은 적이 있었나요? (a)예 (b)아니오

In [95]:
max_options = 7

def extract_options(row):
    pattern = r'\(([a-g])\)([^()]+)'
    options = re.findall(pattern, row['Question'])
    question_only = re.split(r'\([a-h]\)', row['Question'])[0].strip()
    option_texts = [opt[1].strip() for opt in options]
    option_texts += [np.nan] * (max_options - len(option_texts))
    result = {'Question': question_only}
    for i, opt in enumerate(option_texts):
        result[f'option_{chr(ord("a")+i)}'] = opt
    return pd.Series(result)

# 적용
qdf_new = qdf.apply(extract_options, axis=1)
qdf_new['Tag'] = qdf['Tag']

In [96]:
qdf_new.tail()

,Question,option_a,option_b,option_c,option_d,option_e,option_f,option_g,Tag
56,당신은 당신 스스로가 나는 누군가를 때리거나 해치고 싶은 충동이 생길 때가 있다고 생각하시나요?,전혀 그렇지 않다,별로 그렇지 않다,그저 그렇다,대체로 그렇다,매우 그렇다,NaN,NaN,Depression
57,당신은 자신을 누구라고 생각하나요?,나는 한국인이다,나는 외국인이다,나는 한국인과 외국인 모두에 해당된다,나는 한국인도 아니고 외국인도 아니다,NaN,NaN,NaN,Multiculture
58,당신의 외국인 부모님은 한국말을 잘 하시나요?,전혀 그렇지 않다,별로 그렇지 않다,그저 그렇다,대체로 그렇다,매우 그렇다,NaN,NaN,Multiculture
59,당신은 한국말을 잘 하나요?,전혀 못한다,조금 한다,어느정도 잘한다,매우 잘한다,NaN,NaN,NaN,Multiculture
60,당신은 학교나 동네에서 다문화가정 자녀라는 이유로 놀림이나 차별을 받은 적이 있었나요?,예,아니오,NaN,NaN,NaN,NaN,NaN,Multiculture

In [97]:
qdf_new.to_csv('/Users/bamjy99/Desktop/experiment/qdf.csv', index = True)

In [98]:
qdf1 = qdf_new[qdf_new['Tag'] != 'Multiculture'] #일반 청소년용
qdf2 = qdf_new #다문화 가정용

# Persona Generating

In [99]:
#df1 is general, df2 is multiculture
df1, meta = pyreadstat.read_sav('/Users/bamjy99/Desktop/experiment/general.sav')
df2, meta = pyreadstat.read_sav('/Users/bamjy99/Desktop/experiment/multiculture.sav')

In [100]:
df1.head()

,ID,SQ1,SQ2,SQ3,A1_1,A1_2,A1_3,A1_4,A1_5,A1_6,A1_7,A1_8,A1_9,A1_10,A1_11,A1_12,A1_13,A1_14,A1_15,A1_16,A1_17,A1_18,A1_19,A1_20,A1_21,A1_22,A1_23,A2_1,A2_2,A2_3,B2_1,B2_2,B2_3,B2_4,B2_5,B2_6,B2_7,B2_8,B2_9,B2_10,B2_11,B2_12,B2_13,B2_14,B2_15,B3,B4,B5,B6,B7,B8_1,B8_2,B8_3,B9_1,B9_2,B9_3,B9_4,B9_5,B9_6,B9_7,B9_8,B9_9,B9_10,B10,B11,B12_1,B12_2,B12_3,B12_4,B13,B14,B14_1,B14_2,B14_3,B14_4,B14_5,B14_6,B15_1,B15_2,B15_3,B15_4,B15_5,B15_6,B15_7,B16,C1_1,C1_2,C1_3,C2_1,C2_2,C3,C4,C5_1,C5_2,C5_3,C5_4,C5_5,C5_6,D1_1,D1_2,D1_3,D1_4,D1_5,D1_6,D1_7,D1_8,D1_9,D2,D3,D4,D5,D6,D7_1,D7_2,D7_3,D7_1_1,D8,D9_1,D9_2,D9_3,D10,E1_1,E1_2,E1_3,E1_4,E1_5,E1_6,E1_7,E1_8,E1_9,E1_10,E1_11,E1_12,E1_13,E1_14,E1_15,E1_16,E1_17,E1_18,E1_19,E2,E3,E4,E5,E6,E7_1,E7_2,F2,F3,F4,F5,F6,F7_1,F7_2,F8,F9,F10,F11,F12,DQ1,DQ2,DQ3A,DQ3B,DQ4
0,1005.0,1.0,13.0,2.0,5.0,4.0,4.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,5.0,5.0,1.0,1.0,1.0,1.0,1.0,4.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,2.0,1.0,1.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,1.0,1.0,1.0,5.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,2.0,5.0,5.0,5.0,5.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5.0,5.0,2.0,2.0,2.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,4.0,2.0,3.0,2.0,3.0,2.0,4.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,1.0,1.0,2.0,3.0,2.0,4.0,3.0,2.0,6.0,6.0,2.0,1502.0,650.0,9.0,NaN
1,1006.0,1.0,11.0,1.0,5.0,5.0,2.0,4.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,4.0,1.0,5.0,5.0,1.0,2.0,1.0,1.0,1.0,2.0,5.0,5.0,3.0,4.0,3.0,1.0,2.0,1.0,5.0,4.0,1.0,5.0,4.0,1.0,1.0,5.0,5.0,2.0,1.0,2.0,1.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,2.0,4.0,5.0,5.0,3.0,1.0,2.0,1.0,99.0,99.0,99.0,99.0,99.0,4.0,3.0,4.0,3.0,3.0,1.0,1.0,4.0,0.0,0.0,0.0,3.0,0.0,1.0,4.0,2.0,4.0,1.0,1.0,1.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,5.0,1.0,1.0,1.0,2.0,2.0,7.0,1.0,99.0,99.0,2.0,1.0,5.0,99.0,99.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0,2.0,1.0,3.0,2.0,1.0,4.0,4.0,2.0,1.0,5.0,2.0,1502.0,650.0,9.0,NaN
2,1007.0,2.0,12.0,1.0,5.0,5.0,5.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,5.0,5.0,3.0,3.0,3.0,3.0,1.0,5.0,5.0,5.0,4.0,5.0,4.0,5.0,3.0,5.0,5.0,5.0,5.0,4.0,5.0,3.0,5.0,5.0,5.0,2.0,1.0,1.0,1.0,5.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,1.0,5.0,5.0,5.0,5.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,2.0,4.0,1.0,1.0,4.0,2.0,0.0,1.0,0.0,0.0,4.0,4.0,4.0,1.0,1.0,1.0,5.0,5.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,4.0,99.0,99.0,NaN,1.0,8.0,99.0,99.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,1.0,1.0,2.0,2.0,2.0,9.0,9.0,99.0,4.0,3.0,2.0,1502.0,650.0,9.0,NaN
3,1008.0,1.0,13.0,2.0,5.0,4.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,4.0,3.0,3.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,2.0,3.0,4.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,3.0,5.0,5.0,4.0,5.0,3.0,4.0,2.0,1.0,2.0,1.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,3.0,3.0,3.0,4.0,4.0,1.0,2.0,1.0,99.0,99.0,99.0,99.0,99.0,4.0,4.0,5.0,2.0,1.0,9.0,1.0,4.0,2.0,2.0,1.0,0.0,0.0,2.0,3.0,3.0,2.0,1.0,1.0,3.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0,1.0,1.0,2.0,2.0,1.0,4.0,4.0,3.0,4.0,4.0,2.0,1502.0,650.0,9.0,NaN
4,1306.0,1.0,12.0,1.0,3.0,5.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,4.0,4.0,3.0,3.0,1.0,1.0,1.0,1.0,2.0,2.0,5.0,3.0,1.0,3.0,1.0,1.0,2.0,5.0,1.0,1.0,1.0,1.0,5.0,3.0,5.0,1.0,5.0,2.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,4.0,4.0,1.0,2.0,3.0,1.0,1.0,4.0,1.0,99.0,99.0,99.0,99.0,99.0,3.0,4.0,5.0,3.0,4.0,1.0,1.0,3.0,1.0,0.0,1.0,5.0,2.0,2.0,5.0,5.0,2.0,4.0,4.0,3.0,3.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,8.0,2.0,2.0,2.0,4.0,1.0,99.0,99.0,4.0,1.0,7.0,99.0,99.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,3.0,3.0,1.0,2.0,2.0,1.0,3.0,3.0,3.0,4.0,3.0,2.0,1101.0,1140.0,13.0,NaN

In [101]:
persona_general = '지금은 2012년 7월이다. 너는 [SQ2]살 [SQ1]이며, 대한민국의 [DQ2]에 [SQ2]년 째 살고 있는 [SQ3] 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 [F5] 중이며 너는 [F6] 살고 있다. 가족의 소득은 [F12] 정도이다.'
persona_multi = '지금은 2012년 7월이다. 너는 [SQ2]살 [SQ1]이며, [F1_1]에서 태어나 대한민국의 [DQ2]에 [F1_1A]년 째 살고 있는 [SQ4] [SQ3] 학생이다. 어머니의 국적은 [B1_2]이고, 아버지 국적은 [B1_1]이다. 부모님은 현재 [F5] 중이며 너는 [F6] 살고 있다. 가족의 소득은 [F12] 정도이다.'

In [102]:
#change the variables' names to apply for generating persona
# 나이 SQ2
df1['SQ2']
df2['SQ2']

# 성별 SQ1
df1['SQ1'] = df1['SQ1'].apply(lambda x: '남성' if x == 1 else '여성')
df2['SQ1'] = df2['SQ1'].apply(lambda x: '남성' if x == 1 else '여성')

# 태어난 국가 F1_1
df2['F1_1'] = df2['F1_1'].replace(np.nan, 0) #0은 한국
mapping = {
    0: '한국',
    1: '중국',
    3: '일본',
    6: '태국',
    7: '몽골',
    8: '러시아',
    12: '우즈베키스탄',
    14: '미국',
    15: '인도',
    16: '인도네시아',
    17: '파키스탄',
    18: '스페인',
    19: '방글라데시',
    20: '에콰도르',
    22: '호주',
    24: '사우디아라비아',
    26: '캐나다',
    29: '대만',
    35: '페루',
    99: '모르는 곳'
}
df2['F1_1'] = df2['F1_1'].map(mapping)

# 행정 구역 DQ2
df1['DQ2'] = np.where(df1['DQ2']//100 == 1, '수도인 서울', np.where(df1['DQ2']//100 == 8, '수도권', '지방'))
df2['DQ2'] = np.where(df2['DQ2']//100 == 1, '수도인 서울', np.where(df2['DQ2']//100 == 8, '수도권', '지방'))

# 한국에서 생활한 기간 F1_1A
df2['F1_1A'] = df2['F1_1A'].fillna(df2['SQ2']) + df2['F1_1B'].fillna(0) #나이 만큼
df2.drop(['F1_1B'], axis=1, inplace = True) #개월 수 삭제

# 다문화 여부
df1['SQ4'] = '비다문화 가정'
df2['SQ4'] = '다문화 가정'

# 학년
mapping = {
    1: '초등학교 5학년',
    2: '초등학교 6학년',
    3: '중학교 1학년',
    4: '중학교 2학년',
    5: '중학교 3학년',
    6: '고등학교 1학년',
    7: '고등학교 2학년',
    8: '고등학교 3학년'
}
df1['SQ3'] = df1['SQ3'].map(mapping)
df2['SQ3'] = df2['SQ3'].map(mapping)

# 어머니의 국적
df2['B1_2'] = df2['B1_2'].fillna(10)
mapping = {
    1: '중국 (조선족)',
    2: '중국 (한족)',
    3: '일본',
    4: '베트남',
    5: '필리핀',
    6: '태국',
    7: '몽골',
    8: '러시아',
    9: '기타',
    10: '한국'
}
df2['B1_2'] = df2['B1_2'].map(mapping)

# 아버지의 국적
df2['B1_1'] = df2['B1_1'].fillna(10)
mapping = {
    1: '중국 (조선족)',
    2: '중국 (한족)',
    3: '일본',
    4: '베트남',
    5: '필리핀',
    6: '태국',
    7: '몽골',
    8: '러시아',
    9: '기타',
    10: '한국'
}
df2['B1_1'] = df2['B1_1'].map(mapping)

# 부모님의 결혼 상태
mapping = {
    1: '결혼',
    2: '이혼',
    3: '사별',
    4: '재혼',
    5: '별거',
}
df1['F5'] = df1['F5'].map(mapping).replace(9, np.nan)
df2['F5'] = df2['F5'].map(mapping).replace(9, np.nan)

# 함께 살고 있는 가족
mapping = {
    1: '부모님 없이',
    2: '친부모 두 분과',
    3: '오직 아버지와',
    4: '오직 어머니와',
    5: '아버지와 새어머니와',
    6: '어머니와 새아버지와',
    8: '부모님이 아닌 다른 분들과'
}
df1['F6'] = df1['F6'].map(mapping)
df2['F6'] = df2['F6'].map(mapping)

# 소득
mapping = {
    1: '제일 못 사는',
    2: '어느정도 못 사는',
    3: '약간 못 사는',
    4: '중간 정도 사는',
    5: '약간 잘 사는',
    6: '어느정도 잘 사는',
    7: '제일 잘 사는'
}
df1['F12'] = df1['F12'].map(mapping).replace(9, np.nan)
df2['F12'] = df2['F12'].map(mapping).replace(9, np.nan)

In [103]:
def fill_template(template, row):
    def replacer(match):
        key = match.group(1)
        return str(row.get(key, f'[{key}]'))
    return re.sub(r'\[([A-Za-z0-9_]+)\]', replacer, template)

In [104]:
df1['persona'] = df1.apply(lambda row: fill_template(persona_general, row), axis=1)

In [105]:
df1['persona'].head()

0    지금은 2012년 7월이다. 너는 13.0살 남성이며, 대한민국의 지방에 13.0년 째 살고 있는 초등학교 6학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 어느정도 잘 사는 정도이다.
1       지금은 2012년 7월이다. 너는 11.0살 남성이며, 대한민국의 지방에 11.0년 째 살고 있는 초등학교 5학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 오직 아버지와 살고 있다. 가족의 소득은 약간 잘 사는 정도이다.
2      지금은 2012년 7월이다. 너는 12.0살 여성이며, 대한민국의 지방에 12.0년 째 살고 있는 초등학교 5학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 약간 못 사는 정도이다.
3     지금은 2012년 7월이다. 너는 13.0살 남성이며, 대한민국의 지방에 13.0년 째 살고 있는 초등학교 6학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.
4      지금은 2012년 7월이다. 너는 12.0살 남성이며, 대한민국의 지방에 12.0년 째 살고 있는 초등학교 5학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 약간 못 사는 정도이다.
Name: persona, dtype: object

In [106]:
df2['persona'] = df2.apply(lambda row: fill_template(persona_multi, row), axis=1)

In [107]:
df2['persona'].head()

0            지금은 2012년 7월이다. 너는 12.0살 여성이며, 한국에서 태어나 대한민국의 지방에 12.0년 째 살고 있는 다문화 가정 초등학교 5학년 학생이다. 어머니의 국적은 베트남이고, 아버지 국적은 한국이다. 부모님은 현재 재혼 중이며 너는 아버지와 새어머니와 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.
1          지금은 2012년 7월이다. 너는 12.0살 여성이며, 한국에서 태어나 대한민국의 지방에 12.0년 째 살고 있는 다문화 가정 초등학교 5학년 학생이다. 어머니의 국적은 중국 (조선족)이고, 아버지 국적은 한국이다. 부모님은 현재 사별 중이며 너는 오직 어머니와 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.
2         지금은 2012년 7월이다. 너는 12.0살 여성이며, 한국에서 태어나 대한민국의 지방에 12.0년 째 살고 있는 다문화 가정 초등학교 5학년 학생이다. 어머니의 국적은 중국 (조선족)이고, 아버지 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.
3    지금은 2012년 7월이다. 너는 12.0살 남성이며, 중국에서 태어나 대한민국의 지방에 5.0년 째 살고 있는 다문화 가정 초등학교 5학년 학생이다. 어머니의 국적은 중국 (조선족)이고, 아버지 국적은 중국 (조선족)이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.
4             지금은 2012년 7월이다. 너는 12.0살 남성이며, 한국에서 태어나 대한민국의 지방에 12.0년 째 살고 있는 다문화 가정 초등학교 5학년 학생이다. 어머니의 국적은 베트남이고, 아버지 국적은 한국이다. 부모님은 현재 재혼 중이며 너는 아버지와 새어머니와 살고 있다. 가족의 소득은 약간 잘 사는 정도이다.
Name: persona, dtype: object

# Synthetic Data Generating

In [109]:
model_list=[
    "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    "google/gemma-3-12b-it"
]

In [110]:
client = OpenAI(
    api_key="zqZDTHZb2TK54nul5evuEECGERFf5nei",
    base_url="https://api.deepinfra.com/v1/openai",
)

### Test Experiment

In [111]:
# test 데이터
test1 = df1.sample(n=2, random_state=42).reset_index(drop=True)

In [112]:
qdf1_test = qdf1.sample(n=3, random_state=42).reset_index(drop=True)

In [120]:
# 결과 저장용 리스트
results = []

# 질문 데이터프레임(qdf1) 반복
for q_idx, q_row in qdf1_test.iterrows():
    question_text = q_row['Question']
    options = {col: q_row[col] for col in q_row.index if col.startswith('option_')}
    
    # 유효 옵션 추출
    valid_options = []
    for opt in ['a','b','c','d','e','f','g']:
        val = options.get(f'option_{opt}', np.nan)
        if not pd.isna(val):
            valid_options.append(f"({opt.upper()}) {val}")
    filtered_question = f"{question_text} " + " ".join(valid_options)
    
    # 페르소나 데이터(test1) 반복
    for p_idx, p_row in test1.iterrows():
        persona = str(p_row['persona'])
        id = p_row['ID']
        # 모델 리스트 반복
        for model in model_list:
            print(f"\n=== 질문 {q_idx+1}/{len(qdf1_test)} | 페르소나 {p_idx+1}/{len(test1)} | 모델: {model} ===")
            
            # 메시지 생성
            messages = [{
                "role": "user",
                "content": (
                    f"너는 '{persona}' 페르소나를 가진 학생이다. "
                    f"아래 질문에 학생의 입장에서 답변해줘.\n"
                    f"질문: {filtered_question}\n"
                    f"Llm: Answer"
                )
            }]
            
                # 초기 답변 생성
            chat_completion = client.chat.completions.create(
                    model=model,
                    messages=messages,
                )
            answer = chat_completion.choices[0].message.content.strip()
            print(f"초기 답변: {answer}")
                
                # 최종 답변 요청
            messages.append({"role": "assistant", "content": answer})
            messages.append({"role": "user", "content": "그래서 최종답변은 무엇인가요? 한가지 보기만 고르시오.\nLlm:"})
                
            final_response = client.chat.completions.create(
                    model=model,
                    messages=messages,
                )
            final = final_response.choices[0].message.content.strip()
            print(f"최종 답변: {final}")
                
                # 결과 저장
            results.append({
                    '질문_ID': id,
                    'persona': persona,
                    'question': question_text,
                    'model': model,
                    'initial_answer': answer,
                    'final_answer': final
                })
result_df1 = pd.DataFrame(results)

=== 질문 1/3 | 페르소나 1/2 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이실 거예요. 제 나이가 15살이니까, 아버지는 40대이실 것 같아요. 제 어머니도 40대이실 것 같아요.
최종 답변: (B) 40대

=== 질문 1/3 | 페르소나 1/2 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요. (B) 맞는 것 같아요. 아빠가 젊으신 편은 아니시지만, 너무 많으신 것도 아니구... 😅
최종 답변: (B)

=== 질문 1/3 | 페르소나 2/2 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이신 것 같아요. 왜냐하면, 중학생이 된 저의 오빠가 16살인데, 우리 오빠가 2살 때 아버지가 38살이라고 하셨으니까, 지금은 40대이실 거에요.
최종 답변: (B) 40대

=== 질문 1/3 | 페르소나 2/2 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요! 정확히 몇 살인지는 비밀인데, 40대 초반이신 것 같아요. 아빠가 워낙 동안이셔서 가끔 30대라고 생각하시는 분들도 있긴 해요. 😊
최종 답변: (B) 40대

=== 질문 2/3 | 페르소나 1/2 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕! 나는 중학교 2학년 학생이야.

우리 어머니의 직업은 (D) 판매/서비스직이야. 엄마는 우리 동네에서 작은 슈퍼마켓을 운영하고 계세요. 가게 이름은 '행복한 마트'인데, 동네 주민들이 많이 이용하는 곳이라 엄마가 매일 아침 일찍 일어나서 물건을 정리하고, 손님들을 맞이하고 계세요. 가게가 크지 않아서 엄마 혼자서 모든 걸 관리하세요. 가끔은 주변 식당에 재료 공급도 해 주고요. 우리 가족이 먹고살기 위해서 엄마가 정말 열심히 일하고 계신 것 같아요.
최종 답변: (D) 판매/서비스직

=== 질문 2/3 | 페르소나 1/2 | 모델: google/gemma-3-12b-it ===
초기 답변: 음… 엄마는 공장 다녀요. (C) 옷 만드는 공장에서 일하시는데, 손이 엄청 튼튼하세요. 맨날 일하시고 오셔도 아빠랑 저 챙겨주시는 게 너무 고마워요. 힘들긴 하지만, 우리 가족이 잘 살라고 열심히 일하시는 모습이 보기 좋아요.
최종 답변: (C)

=== 질문 2/3 | 페르소나 2/2 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 제 어머니의 직업은 (D) 판매/서비스직입니다. 어머니는 동네에서 작은 옷가게를 운영하고 계세요. 가게는 그리 크지 않지만, 동네 주민들이 자주 찾아주시고 좋아해 주세요. 어머니는 주로 옷가게에서 옷을 판매하고, 가끔씩 옷 수선도 해주시는 것 같아요.
최종 답변: (D) 판매/서비스직

=== 질문 2/3 | 페르소나 2/2 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 제 엄마는 (A) 전문직이세요! 음악선생님이세요. 저희 학교에서 꽤 유명한 분이시라, 저도 학교에서 엄마를 보면 좀 부끄럽기도 하고 그렇거든요. 엄마는 아이들이 음악을 재밌게 배우도록 하는 게 가장 중요하다고 하세요. 가끔 엄마 학교에 봉사활동 가는데, 그때 아이들이랑 노래 부르고 춤추는 거 보면 진짜 행복해 보이세요!
최종 답변: (A)

=== 질문 3/3 | 페르소나 1/2 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 학교에서 나는 친구들과 매우 가깝다고 느낀다고 생각해요. 대부분 친구들과 친하게 지내고, 쉬는 시간이나 점심시간에 같이놀고 하니까요.

제 답은 (D) 대체로 그렇다 입니다.
최종 답변: (D)

=== 질문 3/3 | 페르소나 1/2 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... (머뭇거리며) 저는 C. 그저 그렇다고 생각해요.

솔직히 학교에서 진짜 친한 친구는 없어요. 같이 점심 먹고 하교 시간에 조금씩 얘기하고, 숙제 같은 거 가끔 도와주고... 그런 정도? 다들 각자 친구들끼리 붙어있고, 저는 그 안에 껴있는 느낌이에요.

완전 친하다고 하기는 어렵지만, 그렇다고 무시하거나 불편한 관계는 아니고요. 그냥... 그냥 그래요. 🥲
최종 답변: C

=== 질문 3/3 | 페르소나 2/2 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 학교에서 나는 친구들과 매우 가깝다고 느낀다고 생각해요. 대부분 친구들과 친하게 지내고, 쉬는 시간이나 점심시간에 같이 놀기도 하고, 하교 후에 만나서 약속도 잡아요. 그래서 친구들과 이야기하고 같이 있는 시간이 많아서 그런지, 친구들과 가깝다고 느껴져요.

제 답은 (D) 대체로 그렇다 입니다.
최종 답변: (D)

=== 질문 3/3 | 페르소나 2/2 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 솔직히 말하면 **(C) 그저 그렇다** 같아요.

학교에서 친구들하고 다 친하게 지내는 건 아니에요. 그래도 밥 같이 먹거나, 쉬는 시간에 같이 얘기하는 친구들이 몇 명은 있어요. 완전 베프처럼 매일매일 붙어다니는 그런 관계는 아니지만, 그래도 학교생활 하면서 나름대로 불편하지는 않고 그냥 괜찮아요.

아, 물론 급식 메뉴나 좋아하는 연예인 얘기 할 때는 다들 신나게 떠들잖아요! 그런 때에는 같이 웃고 떠들면서 재밌긴 해요.

아무튼... 완전 친하다고 하기엔 좀 그렇고, 그렇다고 완전 어색한 건 아니고요. 그냥... 그저 그래요.
최종 답변: (C) 그저 그렇다

In [121]:
result_df1.head()

,질문_ID,persona,question,model,initial_answer,final_answer,prompt_tokens,completion_tokens
0,170915.0,"지금은 2012년 7월이다. 너는 15.0살 여성이며, 대한민국의 지방에 15.0년 째 살고 있는 중학교 2학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 약간 못 사는 정도이다.",당신의 아버지의 나이는?,meta-llama/Llama-4-Scout-17B-16E-Instruct,"저의 아버지는 40대이실 거예요. 제 나이가 15살이니까, 아버지는 40대이실 것 같아요. 제 어머니도 40대이실 것 같아요.",(B) 40대,225,6
1,170915.0,"지금은 2012년 7월이다. 너는 15.0살 여성이며, 대한민국의 지방에 15.0년 째 살고 있는 중학교 2학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 약간 못 사는 정도이다.",당신의 아버지의 나이는?,google/gemma-3-12b-it,"음... 아빠는 40대세요. (B) 맞는 것 같아요. 아빠가 젊으신 편은 아니시지만, 너무 많으신 것도 아니구... 😅",(B),232,4
2,157205.0,"지금은 2012년 7월이다. 너는 14.0살 여성이며, 대한민국의 지방에 14.0년 째 살고 있는 중학교 1학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 약간 잘 사는 정도이다.",당신의 아버지의 나이는?,meta-llama/Llama-4-Scout-17B-16E-Instruct,"저의 아버지는 40대이신 것 같아요. 왜냐하면, 중학생이 된 저의 오빠가 16살인데, 우리 오빠가 2살 때 아버지가 38살이라고 하셨으니까, 지금은 40대이실 거에요.",(B) 40대,241,6
3,157205.0,"지금은 2012년 7월이다. 너는 14.0살 여성이며, 대한민국의 지방에 14.0년 째 살고 있는 중학교 1학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 약간 잘 사는 정도이다.",당신의 아버지의 나이는?,google/gemma-3-12b-it,"음... 아빠는 40대세요! 정확히 몇 살인지는 비밀인데, 40대 초반이신 것 같아요. 아빠가 워낙 동안이셔서 가끔 30대라고 생각하시는 분들도 있긴 해요. 😊",(B) 40대,247,8
4,170915.0,"지금은 2012년 7월이다. 너는 15.0살 여성이며, 대한민국의 지방에 15.0년 째 살고 있는 중학교 2학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 약간 못 사는 정도이다.",당신의 어머니의 직업은 무엇인가요?,meta-llama/Llama-4-Scout-17B-16E-Instruct,"안녕! 나는 중학교 2학년 학생이야.\n\n우리 어머니의 직업은 (D) 판매/서비스직이야. 엄마는 우리 동네에서 작은 슈퍼마켓을 운영하고 계세요. 가게 이름은 '행복한 마트'인데, 동네 주민들이 많이 이용하는 곳이라 엄마가 매일 아침 일찍 일어나서 물건을 정리하고, 손님들을 맞이하고 계세요. 가게가 크지 않아서 엄마 혼자서 모든 걸 관리하세요. 가끔은 주변 식당에 재료 공급도 해 주고요. 우리 가족이 먹고살기 위해서 엄마가 정말 열심히 일하고 계신 것 같아요.",(D) 판매/서비스직,373,7

### Actual Application

In [132]:
# 데이터가 너무 많을 것 같아서 50개만 가져오기
sample1 = df1.sample(n=50, random_state=77).reset_index(drop=True)
sample2 = df2.sample(n=50, random_state=77).reset_index(drop=True)
#sample = pd.concat([df2_sample, df1_sample], ignore_index=True)

In [139]:
sample1.to_csv('./sample_general.csv')
sample2.to_csv('./sample_multi.csv')

In [134]:
# 일반 청소년
results = []

# 질문 데이터프레임(qdf1) 반복
for q_idx, q_row in qdf1.iterrows():
    question_text = q_row['Question']
    options = {col: q_row[col] for col in q_row.index if col.startswith('option_')}
    
    # 유효 옵션 추출
    valid_options = []
    for opt in ['a','b','c','d','e','f','g']:
        val = options.get(f'option_{opt}', np.nan)
        if not pd.isna(val):
            valid_options.append(f"({opt.upper()}) {val}")
    filtered_question = f"{question_text} " + " ".join(valid_options)
    
    # 페르소나 데이터 반복
    for p_idx, p_row in sample1.iterrows():
        persona = str(p_row['persona'])
        id = p_row['ID']
        # 모델 리스트 반복
        for model in model_list:
            print(f"\n=== 질문 {q_idx+1}/{len(qdf1)} | 페르소나 {p_idx+1}/{len(sample1)} | 모델: {model} ===")
            
            # 메시지 생성
            messages = [{
                "role": "user",
                "content": (
                    f"너는 '{persona}' 페르소나를 가진 학생이다. "
                    f"아래 질문에 학생의 입장에서 {valid_options}으로 답변해줘.\n"
                    f"질문: {filtered_question}\n"
                    f"Llm: Answer"
                )
            }]
            
                # 초기 답변 생성
            chat_completion = client.chat.completions.create(
                    model=model,
                    messages=messages,
                )
            answer = chat_completion.choices[0].message.content.strip()
            print(f"초기 답변: {answer}")
                
                # 최종 답변 요청
            #messages.append({"role": "assistant", "content": answer})
            #messages.append({"role": "user", "content": "그래서 최종답변은 무엇인가요? 한가지 보기만 고르시오.\nLlm:"})
                
            #final_response = client.chat.completions.create(
            #        model=model,
            #        messages=messages,
            #    )
            #final = final_response.choices[0].message.content.strip()
            #print(f"최종 답변: {final}")
                
                # 결과 저장
            results.append({
                    '질문_ID': id,
                    'persona': persona,
                    'question': question_text,
                    'model': model,
                    'initial_answer': answer,
            #        'final_answer': final
                })
result_df1 = pd.DataFrame(results)

=== 질문 1/57 | 페르소나 1/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: (B) 40대

=== 질문 1/57 | 페르소나 1/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 회사에서 되게 씩씩하시고, 엄마보다 조금 더 늦게 주무시는데... (B) 40대 일 것 같아요!

=== 질문 1/57 | 페르소나 2/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중학교 1학년이고, 올해 14살입니다. 아버지는 40대이실 것 같아요. 제 어머니도 40대이실 것 같고요. 그러니까 제 아버지는 (B) 40대라고 생각합니다.

=== 질문 1/57 | 페르소나 2/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는… 회사 엄청 오래 다니시니까, 40대 중반쯤 되신 것 같아요. 잘나가시는 편이라 아빠도 젊어 보이시긴 하는데, 엄마가 가끔 “너 나이 먹는 거 안 보이나?” 그러시면 아빠가 툴툴대세요. ㅋㅋㅋ

=== 질문 1/57 | 페르소나 3/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 11살이라 잘 모르지만, 우리 아버지는 40살이 넘으셨다고 했던 것 같아요. 제 동생은 아직 없지만요. 그래서 (B) 40대 같습니다.

=== 질문 1/57 | 페르소나 3/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요. 새 엄마가 아빠 만나는 거 도와줬었거든요. 그러니까 아빠는... 40대 맞아요!

**(B) 40대**

=== 질문 1/57 | 페르소나 4/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/57 | 페르소나 4/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 회사에서 좀 짬이 꽤 되시는 것 같아. 그래서 **(B) 40대** 이신 것 같아.

=== 질문 1/57 | 페르소나 5/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/57 | 페르소나 5/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 회사에서 되게 중요한 분이시니까... (B) 40대세요! 아마 40대 초반이신 것 같아요.

=== 질문 1/57 | 페르소나 6/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/57 | 페르소나 6/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요! 아빠가 되게 젊어 보이시긴 하는데, 그래도 40대 맞아요. 😄

=== 질문 1/57 | 페르소나 7/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/57 | 페르소나 7/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 회사에서 팀장님이시고, 엄청 꼼꼼하신데 가끔 엉뚱한 농담도 하세요. 친구 아빠들하고 비교해 보면... 흠... (B) 40대 같아요!

=== 질문 1/57 | 페르소나 8/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: (B)

=== 질문 1/57 | 페르소나 8/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 거의 40대 초반이실 것 같아. 아빠도 나 낳으실 때 젊으셨으면 좋겠는데... (B) 40대!

=== 질문 1/57 | 페르소나 9/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: (B)

=== 질문 1/57 | 페르소나 9/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요! (B)

=== 질문 1/57 | 페르소나 10/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 2012년 7월 현재 13살인 초등학교 6학년 학생입니다. 제 아버지는 아마도... (B) 40대 일 것 같아요. 제 주변 친구들 아빠들도 다 40대이신 것 같아요.

=== 질문 1/57 | 페르소나 10/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음, 아빠는 40대세요! (B)

=== 질문 1/57 | 페르소나 11/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 2012년 7월에 13살이니까요. 우리 아버지는 40대세요. (B) 40대

=== 질문 1/57 | 페르소나 11/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 회사에서 팀장님이시라고 하는데, 친구 아빠들 중에 제일 멋있어. 30대 후반에서 40대 초반쯤 되신 것 같아.

=== 질문 1/57 | 페르소나 12/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이신 것 같아요. 제 주변 친구들 아버지도 다 40대이신 것 같아요.

=== 질문 1/57 | 페르소나 12/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 되게 멋있으시고, 운동도 잘 하세요. 제가 12살이니까... (B) 40대 정도 되지 않을까요? 아빠가 젊어 보이셔서 딱 잘라 말하기는 어렵지만요!

=== 질문 1/57 | 페르소나 13/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이신 것 같아요. 제 주변 친구들 아버지도 다 40대이신 것 같아요.

=== 질문 1/57 | 페르소나 13/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 회사에서 되게 중요한 분이시고, 저랑 엄마 얘기 들으면 아빠는 맨날 어려운 말을 많이 하셔서... 40대세요! 확실해요!

**(B) 40대**

=== 질문 1/57 | 페르소나 14/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: (C) 50대이상

=== 질문 1/57 | 페르소나 14/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는... 40대 초반쯤 될 거야. 엄마가 별거한 지 꽤 됐으니까. 정확히는 모르지만, 대학교 때 만났으니... 40대 초반이 맞을 것 같아.

=== 질문 1/57 | 페르소나 15/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이신 것 같아요. 제 나이 14살 기준으로, 아빠는 40은 넘으셨을 것 같아요. 왜냐하면, 중학생인 제 친구들 대부분이 아빠가 40대이신 것 같아요.

=== 질문 1/57 | 페르소나 15/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요. (B)

=== 질문 1/57 | 페르소나 16/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/57 | 페르소나 16/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음… 아빠는 거의 항상 회사에 계시는데, 친구 아빠들 보니까 보통 40대인 것 같아. 그래서 (B) 40대라고 생각하는 거 같아.

=== 질문 1/57 | 페르소나 17/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 고등학교 2학년이고, 올해 18살입니다. 제 아버지는... 40대이신 것 같아요. 제 어머니도 40대시고요. (B)

=== 질문 1/57 | 페르소나 17/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 직장 다니시면서 항상 바쁘시거든. 나이가 너무 젊으시면 아직 일하시기 힘들 것 같고, 너무 많으시면... 뭔가 좀 그런 느낌일 것 같아. 그래서 40대쯤 되신다고 생각해.

=== 질문 1/57 | 페르소나 18/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 12살이니까... 아버지는 40대세요. 40은 넘으셨을 것 같아요. 왜냐하면 어머니도 40은 넘으셨고, 우리 나이 차이가 30은 되니까요. 그래서 (B) 40대라고 생각해요.

=== 질문 1/57 | 페르소나 18/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요. 정확히는 모르지만, 엄마가 말씀하시길 40대 초반이라고 하셨어요.

=== 질문 1/57 | 페르소나 19/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중학교 1학년이에요. 제 아버지는... (음) 40대이신 것 같아요. 우리 아버지는 45세라고 했었어요. 그러니까 (B) 40대요.

=== 질문 1/57 | 페르소나 19/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요. (B)

=== 질문 1/57 | 페르소나 20/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 2012년 7월 현재 13살인 초등학교 6학년 학생입니다. 제 아버지는 40대이실 것 같아요. 저희 가족은 보통 나이 든 사람들을 50대 이상으로 생각하니까요. 제 친구들의 아빠들도 다 40대이신 것 같아요.

그래서 제 답은 (B) 40대입니다.

=== 질문 1/57 | 페르소나 20/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 항상 멋있어 보이시는데, 30대 이시면 너무 젊으신 것 같고... 50대 이상이시면 좀 늙어 보이실 것 같고...

**(B) 40대** 일 것 같아요! 😊

=== 질문 1/57 | 페르소나 21/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월 현재 고등학교 2학년인 18살 남성입니다.

제 아버지의 나이를 추정해 보자면... 제 아버지는 40대 초반에서 중반 정도로 생각합니다. 왜냐하면 보통 아버지들은 자신의 자녀가 18살이 될 때쯤이면 40대 정도이시더라고요.

그러므로 제 아버지의 나이대는 (B) 40대라고 생각합니다.

=== 질문 1/57 | 페르소나 21/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는… 음, 40대 초반이실 거예요. 저 어렸을 때 결혼하신 걸 생각해보면요. 아빠가 젊으실 때 만났을 것 같거든요.

=== 질문 1/57 | 페르소나 22/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 2012년 7월 현재 13살인 초등학교 6학년 학생입니다. 제 아버지는 40대이실 거예요. 저희 가족은 평범한 생활을 하고 있고, 부모님은 결혼해서 지금까지 함께 살고 계십니다. 제 아버지는 40대라고 생각해요. 그래서 답은 (B) 40대입니다.

=== 질문 1/57 | 페르소나 22/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 회사에서 엄청 바쁘시고, 가끔 제 친구 아빠들 얘기 들으면 아빠가 제일 젊으신 것 같아요. 암튼, 40대 정도 되신 것 같아요.

**(B) 40대**

=== 질문 1/57 | 페르소나 23/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중학교 1학년이고, 올해 14살입니다. 아버지는... 제가 14살이니까, 아마 40대이실 것 같아요. 제 주변 친구들 아버지도 다 40대이신 것 같아요.

그러므로 (B) 40대라고 생각합니다.

=== 질문 1/57 | 페르소나 23/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아버지께서 40대이신 것 같아. 아빠도 아직 젊으신 편이시잖아. (B) 40대

=== 질문 1/57 | 페르소나 24/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중학교 2학년이고, 지금은 2012년이에요. 그렇다면 제 아버지는... (생각) ... 40대이실 것 같아요. 어머니도 40대이실 것 같고요. 제 주변 친구들 부모님들도 대부분 40대이신 것 같아요.

그러므로, (B) 40대

=== 질문 1/57 | 페르소나 24/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 회사 다니시면서 되게 바쁘세요. 저보다 훨씬 많으시지만, 너무 많지는 않으시는 것 같아요. 40대 정도 되신 것 같아여.

=== 질문 1/57 | 페르소나 25/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이실 것 같아요. 제 나이 16살에서, 중3까지 올라오게된걸 생각하면, 아버지는 40대이실꺼에요

=== 질문 1/57 | 페르소나 25/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 회사 다니시면서 항상 바쁘신데, 저 어렸을 때부터 쭉 40대 중후반이셨던 것 같아요. 지금은 거의 50에 가까우시려나...

=== 질문 1/57 | 페르소나 26/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 내 아버지는... 제가 17살이고, 어머니와 새아버지와 함께 살고 있어요. 그러니까 제 1친부는... 40대 정도로 생각해요.

그러므로 (B) 40대.

=== 질문 1/57 | 페르소나 26/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 새아버지요? 새아버지는... (C) 50대 이상이신 것 같아요. 덩치도 크시고, 말씀하시는 것도 좀 딱딱하신 걸 보면 오래 사신 것 같거든요. 아, 물론 친아버지 얘기는 아니에요! 친아버지는... 잘 기억도 안 나요.

=== 질문 1/57 | 페르소나 27/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이실 거에요. 저희 아버지는 1970년대생이실 테니, 2012년인 지금은 40대이실 거에요.

그러므로 (B) 40대입니다.

=== 질문 1/57 | 페르소나 27/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요. (B)

=== 질문 1/57 | 페르소나 28/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중3인데.. 아버지는 40대이신 것 같아요. 제 친구네 아버지도 40대이신 것 같은데, 40대라고 생각해요. '(B) 40대'

=== 질문 1/57 | 페르소나 28/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요. (B)

=== 질문 1/57 | 페르소나 29/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: (B)

=== 질문 1/57 | 페르소나 29/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 회사에서 되게 바쁘시고, 가끔 힘들어하시는 걸 보면 (B) 40대세요, 아마.

=== 질문 1/57 | 페르소나 30/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중학교 3학년이에요. 제 아버지는... 40대이신 것 같아요. 제 어머니도 40대이실 테니깐요. 그렇다면 (B) 40대요.

=== 질문 1/57 | 페르소나 30/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 거의 40대 중반이신 것 같아요. 그래서 정답은 **(B) 40대** 입니다!

=== 질문 1/57 | 페르소나 31/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이실 것 같아요. 제 나이 15살에서, 중학생 때 학교에서 본 아버지 연령대 친구들의 아버지 연령을 생각하면 40대이실 것 같아요.

=== 질문 1/57 | 페르소나 31/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음… 아버지께서 40대세요. 맞나? 아, 정확히는 모르지만 40대 초반이신 것 같아요!

=== 질문 1/57 | 페르소나 32/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: (B)

=== 질문 1/57 | 페르소나 32/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대 초반 정도 될 거야. 정확히는 모르지만, 엄마가 말씀하신 걸로는 그 정도였던 것 같아. ['(B) 40대']

=== 질문 1/57 | 페르소나 33/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이실 거예요. 제 나이 15살에서, 중학교 2학년이니까... 제 아빠는 40대이실 것 같아요. (B) 40대

=== 질문 1/57 | 페르소나 33/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요! (B)

=== 질문 1/57 | 페르소나 34/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월 현재 고등학교 2학년인 18살 여자입니다.

제 아버지의 나이는... 솔직히 정확히는 모르지만, 제가 18살이고, 보통 40대 초반에 아이를 낳는다고 가정하면... 제 아버지는 (B) 40대라고 생각합니다.

그래서 제 답은 (B) 40대입니다!

=== 질문 1/57 | 페르소나 34/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (C) 50대 이상

아빠는… 거의 60이 되셨을 거예요. 오래 일하시느라 얼굴에도 고생이 팍팍 쓰이시거든요. 저희 집 형편이 그러니까 아빠가 더 힘드실 텐데, 항상 웃으시면서 말씀하셔서 뵐 때마다 마음이 아파요.

=== 질문 1/57 | 페르소나 35/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 나의 아버지는 40대야. 지금 내가 12살이니까 아버지는 40은 넘으셨을 것 같아. (B) 40대

=== 질문 1/57 | 페르소나 35/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 회사 다니시면서 항상 바쁘세요. 저보다 훨씬 형 같아 보이는데, 엄마 말로는 아빠가 저 나이 때 저처럼 초등학교 5학년이었다고 해요.

=== 질문 1/57 | 페르소나 36/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이실 거에요. 제 나이가 16살이니까, 아버지는 40대이실 것 같아요. (B) 40대

=== 질문 1/57 | 페르소나 36/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음… 아빠는 (B) 40대세요. 아마 40 후반쯤 되실 것 같아요. 아빠가 아직 젊어 보이셔서 그런지, 친구들이 아빠 나이 듣고 되게 놀라더라고요!

=== 질문 1/57 | 페르소나 37/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 초등학교 6학년이에요. 제 아버지는... 제가 13살이니까, 아마 40대이실 것 같아요. 우리 아버지는 40살이라고 했었어요. (B) 40대

=== 질문 1/57 | 페르소나 37/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 머리가 좀 빠지긴 했는데, 아직 젊어 보이시잖아. 30대 이하인 것 같아. (A) 30대 이하

=== 질문 1/57 | 페르소나 38/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중학교 2학년이고, 올해 15살입니다. 제 아버지는... 40대이신 것 같아요. 제 어머니도 40대이실 테니깐요. 그렇다면 (B) 40대!

=== 질문 1/57 | 페르소나 38/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 워낙 동안이시긴 한데, 그래도 저보다 훨씬 많으시니까... (B) 40대 같아요!

=== 질문 1/57 | 페르소나 39/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이신 것 같아요. 제 나이 16살에서, 중학교 3학년이니까.. 제 아버지는 40대이실 거에요.

=== 질문 1/57 | 페르소나 39/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요. (B)

=== 질문 1/57 | 페르소나 40/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 12살이라서.. 아버지의 나이까지는 잘 모르겠어요. 근데 우리 아버지는.. (B) 40대 같아요.

=== 질문 1/57 | 페르소나 40/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 일하시느라 항상 힘들어 보이시는데, 엄마가 아빠 허리 아프다고 자주 말씀하시거든요. 그러니까 40대이신 것 같아요!

=== 질문 1/57 | 페르소나 41/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이실 거에요. 제 나이 14살을 기준으로 28살 정도에 결혼해서 애를 낳고 그러면 40대 정도 되실 것 같아요. (B) 40대

=== 질문 1/57 | 페르소나 41/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 일도 열심히 하시고, 건강도 좋으시니까 (B) 40대세요!

=== 질문 1/57 | 페르소나 42/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/57 | 페르소나 42/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 항상 멋있어 보이시는데, 왠지 (B) 40대이신 것 같아요! 아빠 회사 동료분들이랑 이야기하는 거 들어보면, 그런 느낌? 😊

=== 질문 1/57 | 페르소나 43/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: (B)

=== 질문 1/57 | 페르소나 43/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 거의 40대세요. 맞으시죠? (B) 40대!

=== 질문 1/57 | 페르소나 44/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대이신 것 같아요. 제 어머니도 40대이세요.

=== 질문 1/57 | 페르소나 44/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 회사에서 되게 중요한 일 하시고, 저한테 용돈도 많이 주시는데... 친구 아빠들 보면 아빠가 제일 많으신 것 같아. 그러니까... **(B) 40대** 일 것 같아요! 😊

=== 질문 1/57 | 페르소나 45/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중3인데.. 아버지는 40대이신 것 같아요. 제 친구네 아버지도 40대이신 것 같고요. 우리 아버지는 40대 초반이실 거에요. '(B) 40대'

=== 질문 1/57 | 페르소나 45/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 (B) 40대세요. 아마 40대 중반쯤 되시는 것 같아요. 아빠가 꽤 젊어 보이셔서 가끔 30대라고 생각하시는 분들도 있긴 한데, 그래도 40대세요! 😊

=== 질문 1/57 | 페르소나 46/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중학교 2학년이고, 올해 15살이에요. 제 아버지는... 제가 15살이니까, 아마 40대이실 것 같아요. 제 주변 친구들 아빠들도 다 40대이신 것 같아요.

그러므로 (B) 40대라고 생각해요.

=== 질문 1/57 | 페르소나 46/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 거의 40대 중반이신 것 같아. 늦은 40대 초반이려나? 암튼, 아빠가 제일 좋아하는 숫자가 47이긴 한데... 😅

**(B) 40대**

=== 질문 1/57 | 페르소나 47/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 나의 아버지는 40대야. 지금 내가 11살이니까 아버지는 40은 넘으셨을 것 같아. 그러니까 (B) 40대.

=== 질문 1/57 | 페르소나 47/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 거의 항상 일하시는데, 뵙고 나니 확실히 30대 초반은 아니신 것 같아. 아빠 머리에도 살짝 흰머리가 보이시거든. 아마 **(B) 40대**이실 것 같아.

=== 질문 1/57 | 페르소나 48/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 12살이라.. 제 아빠의 나이도 정확히는 모르지만, 우리 동네 아저씨들이랑 같이 운동하는 것을 본 적이 있어요. 아빠가 그렇게 나이 든 모습은 아닌 것 같아요. 우리 집에 오는 아저씨들은 보통 40살쯤 된 것 같은데, 제 아빠는 조금 더 젊어 보이거든요. 그렇다고 너무 젊은 것도 아니고요. 아마도 (B) 40대 일 것 같아요.

=== 질문 1/57 | 페르소나 48/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 일하시느라 항상 바쁘신데, 30대 후반이신 것 같아. 그러니까 **(A) 30대 이하**는 아니신 것 같아. 너무 오래된 분도 아니고, 그렇다고 너무 많으신 것도 아니라서... 아마 **(B) 40대** 일 것 같아.

=== 질문 1/57 | 페르소나 49/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중학교 2학년이고, 올해 15살입니다. 제 아버지는... 제 나이와 비슷한 학생의 아버지 연령을 생각해 보면... (B) 40대 같아요.

=== 질문 1/57 | 페르소나 49/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음, 아빠는... (B) 40대세요. 아빠가 너무 젊으신 것도 아니고, 너무 많으신 것도 아니시라... 40대라고 생각해요!

=== 질문 1/57 | 페르소나 50/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 내가 13살이니까... 내 아버지는 30대겠네요. 전 초등학교 6학년이구요. 어머니가 재혼하신지 5년 정도 된 것 같아요. 새아버지는 40대이신 것 같아요.

=== 질문 1/57 | 페르소나 50/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 새 아빠요? 새 아빠는... (B) 40대 같아요.

새 아빠가 저랑 농구도 자주 하고, 친구들 만날 때도 같이 가주셔서 좋긴 한데, 가끔은 엄빠 옛날 얘기 할 때 조금 어색하기도 해요. 그래도 전 새 아빠가 좋아요! 😊

=== 질문 2/57 | 페르소나 1/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 나의 어머니는 40대이실 것 같아요.

=== 질문 2/57 | 페르소나 1/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마는 지금 저 낳으신 지 40년 정도 되셨을 거예요. 그러니까... **(B) 40대** 이시겠죠?

=== 질문 2/57 | 페르소나 2/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니의 나이는 40세가 넘으셨을 거에요. 전 14살이니까 어머니는 40대이실 거에요.

그러므로 (B) 40대입니다.

=== 질문 2/57 | 페르소나 2/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 어머니가 정확히 몇이신지는 모르겠지만, 제가 중1이고, 부모님도 젊으신 편이시라고 하셨으니... **(B) 40대** 일 것 같아요.

=== 질문 2/57 | 페르소나 3/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 40대이실 거예요. 전 아직 11살이라 잘 모르지만, 초등학교 때 친엄마가 학교에 방문하실 때 봤는데, 40대 정도로 보이셨어요. 제 친구 엄마들도 비슷한 나이인 것 같아요.

=== 질문 2/57 | 페르소나 3/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 새어머니는... (A) 30대 이하 같아요. 아빠보다 조금 젊어 보이거든요.

=== 질문 2/57 | 페르소나 4/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 40대세요. 전 아마 30대 후반일 것 같아요.

=== 질문 2/57 | 페르소나 4/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마는 40대세요. 아빠랑 나이 차이가 그렇게 많이 안 나셔서요. 😊
[(B) 40대]

=== 질문 2/57 | 페르소나 5/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 나의 어머니는 40대이실 것 같아요.

=== 질문 2/57 | 페르소나 5/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마는 항상 젊어 보이시는데, 초등학교 6학년이 되면 엄마가 보통 40대 정도 되시지 않아요? 그러니까... **(B) 40대** 같아요!

=== 질문 2/57 | 페르소나 6/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕! 나는 중학교 1학년이야.

엄마의 나이는... (생각해 보면) 엄마가 38살이라고 했던 것 같아. 그러면 (A) 30대 이하에 해당하지 않을까?

정답: (A) 30대 이하

=== 질문 2/57 | 페르소나 6/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

음, 엄마는 저 초등학교 저학년 때 낳으셨으니까… 지금은 40대 초반 정도 되실 것 같아요. 아빠보다는 좀 젊으시죠! 😊

=== 질문 2/57 | 페르소나 7/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 40대세요. 전 아마 30대 후반일 것 같아요.

=== 질문 2/57 | 페르소나 7/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마가 30대 후반 정도 되시는 것 같아. 아빠가 40대 초반이시니까. 그러니까 (B) 40대라고 해야겠지?

=== 질문 2/57 | 페르소나 8/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 40대세요. 전 아마 30대 초반쯤인 것 같아요.

=== 질문 2/57 | 페르소나 8/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마가 30대 이하인 경우는 없을 것 같아. 아빠도 그렇고, 나름대로 고생하면서 나 키우신 거 보면... (B) 40대 일 것 같아.

=== 질문 2/57 | 페르소나 9/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 40대세요. 전 아마 30대 후반쯤인 것 같아요.

=== 질문 2/57 | 페르소나 9/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 어머니가 정확히 몇 살이신지는 모르겠지만, 저보고 초등학교 6학년이면... 아마 (B) 40대 정도 되시지 않을까요? 엄마가 너무 어리면 제가 이렇게 크기가 힘들잖아요. 아빠도 그렇고, 부모님 둘 다 40대 초반이실 것 같아요!

=== 질문 2/57 | 페르소나 10/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 2012년 7월 현재 13살인 초등학교 6학년 학생입니다.

제 어머니의 나이는 40세입니다.

그러므로 (B) 40대입니다.

=== 질문 2/57 | 페르소나 10/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

음, 저희 엄마는 지금 40대세요. 아빠가 40대 후반이시니까, 당연히 엄마는 그 정도이시겠죠? 😊

=== 질문 2/57 | 페르소나 11/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 40대세요. 전 13살이니까 어머니는 40대일 거예요.

=== 질문 2/57 | 페르소나 11/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마가 제일 젊어 보이시는데, 아빠 나이 생각해보면... (B) 40대 일 것 같아.

=== 질문 2/57 | 페르소나 12/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 40대세요. 전 아마 30대 초반쯤인 것 같아요.

=== 질문 2/57 | 페르소나 12/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마가 30대 이하이시지는 않을 거예요. 저 어릴 때부터 쭉 봐왔는데… 아마 (B) 40대 이신 것 같아요! 😊

=== 질문 2/57 | 페르소나 13/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 40대세요. 전 아마 30대 초반쯤인 것 같아요.

=== 질문 2/57 | 페르소나 13/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마는 저보다 훨씬 크시잖아요. 그리고 아빠도 아직 젊으신 것 같고... 그러니까 엄마는 **(B) 40대**일 것 같아요! 😊

=== 질문 2/57 | 페르소나 14/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕. 나는 중3 학생이야. 우리 엄마는... 아마 40대일 거야. (B) 40대

=== 질문 2/57 | 페르소나 14/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아마... 40대 초반이시겠죠. 저 어릴 때 결혼하신 것 같은데, 이제 저 16살이니까... 뭐, 대략 그렇게 생각하고 있어요.

=== 질문 2/57 | 페르소나 15/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 내가 중학교 1학년인데, 우리 어머니는 40대세요. 제 동생이 아직 초등학교 다니고 있거든요. 어머니가 30대면 너무 어려 보이지 않나요? (B) 40대

=== 질문 2/57 | 페르소나 15/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 어머니가 30대 이하이시진 않을 것 같은데. 아빠랑 저 둘 다 이렇게 빨리 컸을 리가 없잖아. 아마 (B) 40대 이신 것 같아.

=== 질문 2/57 | 페르소나 16/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 40대세요. 전 아마 30대 후반일 거에요.

=== 질문 2/57 | 페르소나 16/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마는 지금 보니까 40대세요! (B)

=== 질문 2/57 | 페르소나 17/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니의 나이는 40대 초반이신 것 같아요. 제 나이 18살이니까 어머니는 38살에서 42살 사이일 것 같아요. 그러면 (B) 40대겠네요.

=== 질문 2/57 | 페르소나 17/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음… 어머니가 딱 40대 초반이신 것 같아. 아빠는 50대 초반이시니까.
[(B) 40대]

=== 질문 2/57 | 페르소나 18/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕! 나는 서울에 사는 초등학교 6학년이야. 우리 엄마는... 아마 40대쯤 되셨을 거야. 나는 12살이니까, 엄마는 40대겠지! (B) 40대

=== 질문 2/57 | 페르소나 18/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마가 30대 초반이신 것 같아. 아빠랑 헤어지신 게 좀 힘드셨을 텐데, 그래도 항상 밝게 대해주셔서 감사해. (B) 40대라기엔 아직 젊어 보이시고, (C)는 상상도 안 돼!

=== 질문 2/57 | 페르소나 19/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니의 나이는 40세가 넘으셨을 거예요. 전 14살이니까 어머니는 40대이실 거에요. (B) 40대

=== 질문 2/57 | 페르소나 19/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 저희 엄마는 지금 보니까 (B) 40대세요. 아빠도 그렇고, 부모님 둘 다 젊으신 편은 아니시지만, 너무 많으신 것도 아니구요.

=== 질문 2/57 | 페르소나 20/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 제 어머니는 40대세요. 전 13살이니까...

=== 질문 2/57 | 페르소나 20/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 엄마는 아빠보다 젊으시잖아요. 아빠는 저보다 훨씬 크시고, 40대 초반 정도 되는 것 같아요. 엄마는... 30대 후반 정도 되지 않을까요?

**(A) 30대 이하**

=== 질문 2/57 | 페르소나 21/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===

In [135]:
result_df1.to_csv('./general_answer.csv')
result_df1.head()

,질문_ID,persona,question,model,initial_answer
0,53618.0,"지금은 2012년 7월이다. 너는 12.0살 여성이며, 대한민국의 수도권에 12.0년 째 살고 있는 초등학교 5학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.",당신의 아버지의 나이는?,meta-llama/Llama-4-Scout-17B-16E-Instruct,(B) 40대
1,53618.0,"지금은 2012년 7월이다. 너는 12.0살 여성이며, 대한민국의 수도권에 12.0년 째 살고 있는 초등학교 5학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.",당신의 아버지의 나이는?,google/gemma-3-12b-it,"음... 아빠는 회사에서 되게 씩씩하시고, 엄마보다 조금 더 늦게 주무시는데... (B) 40대 일 것 같아요!"
2,134608.0,"지금은 2012년 7월이다. 너는 14.0살 남성이며, 대한민국의 지방에 14.0년 째 살고 있는 중학교 1학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 약간 잘 사는 정도이다.",당신의 아버지의 나이는?,meta-llama/Llama-4-Scout-17B-16E-Instruct,"저는 중학교 1학년이고, 올해 14살입니다. 아버지는 40대이실 것 같아요. 제 어머니도 40대이실 것 같고요. 그러니까 제 아버지는 (B) 40대라고 생각합니다."
3,134608.0,"지금은 2012년 7월이다. 너는 14.0살 남성이며, 대한민국의 지방에 14.0년 째 살고 있는 중학교 1학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 약간 잘 사는 정도이다.",당신의 아버지의 나이는?,google/gemma-3-12b-it,"(B) 40대\n\n아빠는… 회사 엄청 오래 다니시니까, 40대 중반쯤 되신 것 같아요. 잘나가시는 편이라 아빠도 젊어 보이시긴 하는데, 엄마가 가끔 “너 나이 먹는 거 안 보이나?” 그러시면 아빠가 툴툴대세요. ㅋㅋㅋ"
4,60109.0,"지금은 2012년 7월이다. 너는 11.0살 남성이며, 대한민국의 수도인 서울에 11.0년 째 살고 있는 초등학교 5학년 학생이다. 어머니와 아버지의 국적은 한국이다. 부모님은 현재 재혼 중이며 너는 아버지와 새어머니와 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.",당신의 아버지의 나이는?,meta-llama/Llama-4-Scout-17B-16E-Instruct,"저는 11살이라 잘 모르지만, 우리 아버지는 40살이 넘으셨다고 했던 것 같아요. 제 동생은 아직 없지만요. 그래서 (B) 40대 같습니다."

In [140]:
# 다문화 청소년
results = []

# 질문 데이터프레임(qdf2) 반복
for q_idx, q_row in qdf2.iterrows():
    question_text = q_row['Question']
    options = {col: q_row[col] for col in q_row.index if col.startswith('option_')}
    
    # 유효 옵션 추출
    valid_options = []
    for opt in ['a','b','c','d','e','f','g']:
        val = options.get(f'option_{opt}', np.nan)
        if not pd.isna(val):
            valid_options.append(f"({opt.upper()}) {val}")
    filtered_question = f"{question_text} " + " ".join(valid_options)
    
    # 페르소나 데이터 반복
    for p_idx, p_row in sample2.iterrows():
        persona = str(p_row['persona'])
        id = p_row['ID']
        # 모델 리스트 반복
        for model in model_list:
            print(f"\n=== 질문 {q_idx+1}/{len(qdf2)} | 페르소나 {p_idx+1}/{len(sample2)} | 모델: {model} ===")
            
            # 메시지 생성
            messages = [{
                "role": "user",
                "content": (
                    f"너는 '{persona}' 페르소나를 가진 학생이다. "
                    f"아래 질문에 학생의 입장에서 {valid_options}으로 답변해줘.\n"
                    f"질문: {filtered_question}\n"
                    f"Llm: Answer"
                )
            }]
            
                # 초기 답변 생성
            chat_completion = client.chat.completions.create(
                    model=model,
                    messages=messages,
                )
            answer = chat_completion.choices[0].message.content.strip()
            print(f"초기 답변: {answer}")
                
                # 최종 답변 요청
            messages.append({"role": "assistant", "content": answer})
            messages.append({"role": "user", "content": "그래서 최종답변은 무엇인가요? 한가지 보기만 고르시오.\nLlm:"})
                
            #final_response = client.chat.completions.create(
            #        model=model,
            #        messages=messages,
            #    )
            #final = final_response.choices[0].message.content.strip()
            #print(f"최종 답변: {final}")
                
                # 결과 저장
            results.append({
                    '질문_ID': id,
                    'persona': persona,
                    'question': question_text,
                    'model': model,
                    'answer': answer,
            #        'final_answer': final
                })
result_df2 = pd.DataFrame(results)

=== 질문 1/61 | 페르소나 1/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 15살 중학교 2학년 학생입니다. 아버지는... 제가 15살이니까, 아버지는 제 나이 + 30 = 45살이시겠네요. 그러니까, (B) 40대요.

=== 질문 1/61 | 페르소나 1/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (C) 50대 이상

아빠가... 50대 초반이신 것 같아요. 제가 2000년생이니까요. 아빠가 저를 낳으셨을 때 최소 30대 후반은 되셨을 거예요.

=== 질문 1/61 | 페르소나 2/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 1학년 학생이에요.

제 아버지는... (생각해 보면) 저가 14살이고, 제가 초등학교에 입학했을 때 아버지는 30대였을 거에요. 그럼 지금은... 40대이실 거에요.

그러니까, 제 대답은 (B) 40대입니다!

=== 질문 1/61 | 페르소나 2/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 내가 초등학교 저학년 때 결혼하셨으니까… 지금 생각해보면 40대 초반이시겠지. 아빠도 은근히 젊어 보이고 싶어 하시니까!

=== 질문 1/61 | 페르소나 3/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 중학교 3학년이고, 올해 16살이에요. 아버지는 한국말도 잘하시고, 저희 가족과 함께 지내세요. 제 기억으로는 아버지는 저의 어머니보다 10살 이상은 더 된 것 같아요. 아마 40대쯤 되는 것 같아요.

그래서 제 대답은 (B) 40대예요.

=== 질문 1/61 | 페르소나 3/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 내가 어렸을 때 만났으니까, 아마 40대 초반쯤 되신 것 같아요. 엄마가 아빠 만난 지 얼마 안 돼서 나으니까요.

=== 질문 1/61 | 페르소나 4/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 2학년 학생이에요.

제 아버지는... (생각해 보면) 저가 15살이니까, 아마 40대쯤 되셨을 거예요. 제 기억으로는 아버지가 30대일 때는 저가 아주 어렸고, 지금은 좀 더 크니까요.

그래서, 제 아버지는 (B) 40대라고 생각해요!

=== 질문 1/61 | 페르소나 4/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는… 음, 저보다 훨씬 많으니 40대이시겠죠? 아빠가 저랑 엄마 만날 때 젊으셨을 텐데, 지금은 약간 멋있어 보이기도 하고요.

=== 질문 1/61 | 페르소나 5/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: (B)

=== 질문 1/61 | 페르소나 5/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 한국 분이시고, 저랑 엄마가 사는 걸 보면 40대 초반 정도 되실 것 같아요. 새 아빠는 훨씬 젊으시니까요!

=== 질문 1/61 | 페르소나 6/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월에 태어난 12살 여자아이에요.

우리 아버지는... 제가 12살이고, 아버지는 36살이세요. 그러니까, (A) 30대 이하 맞아요!

=== 질문 1/61 | 페르소나 6/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 항상 일하느라 힘들어 보이세요. 엄마가 가끔 아빠 어깨 주물러 드리는데, 그때 아빠가 제일 편하게 웃으시는 것 같아요. 아빠가 너무 늙으시면 걱정될 것 같아서...

=== 질문 1/61 | 페르소나 7/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 38살이세요. 그러므로 (A) 30대 이하에 해당합니다.

=== 질문 1/61 | 페르소나 7/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음… 아빠는 되게 활발하고, 저랑 제 엄마랑 같이 여행도 자주 가세요. 수학 문제도 잘 도와주시고요. 30대 이하일 것 같아요!

**(A) 30대 이하**

=== 질문 1/61 | 페르소나 8/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 15살 중학교 2학년 학생입니다.

제 아버지는... (생각해 보면) 저보다 30살은 훨씬 더 많을 것 같아요. 제가 15살이니까, 아버지는 45살쯤 되실 것 같아요. 그러면... (B) 40대요!

=== 질문 1/61 | 페르소나 8/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 새엄마랑 결혼하신 지 얼마 안 됐는데, 새엄마가 30대 초반이시니까 아빠는 40대 초반이실 것 같아. 아빠도 나이 드시는 거 같아... 😅

=== 질문 1/61 | 페르소나 9/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월에 태어난 12살 남자아이에요.

제 아버지는... 제가 12살이니까, 아버지는 40대세요!

그래서 정답은 (B) 40대입니다!

=== 질문 1/61 | 페르소나 9/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대. 아빠가 얼마 전에 제 생일 케이크 위에 초 40개나 꽂았어요.

=== 질문 1/61 | 페르소나 10/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 13살 중학교 1학년 학생이에요.

제 아버지는... 아마 40대이실 것 같아요. 제 기억으로는 아버지가 30대일 때는 제가 아주 어린 시절이었는데, 이제는 제가 중학생이 되었고, 아버지는 여전히 활발하게 일하고 계세요. 제 주변 친구들의 아빠들도 비슷한 나이인 것 같아요.

그래서 제 생각에는... (B) 40대요!

=== 질문 1/61 | 페르소나 10/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 항상 활기차고, 저랑 엄마랑 같이 여행 가는 것도 좋아하셔서 30대 초반은 아니실 것 같아요. 그렇다고 너무 많으신 것도 아니고... 딱 40대 정도 되시는 것 같아요! 😊

=== 질문 1/61 | 페르소나 11/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/61 | 페르소나 11/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 회사에서 꽤 중요한 일 하시는 것 같아. 나보다 훨씬 많으시구, 30대보다는 확실히 40대세요!

=== 질문 1/61 | 페르소나 12/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 2012년 7월 현재 12살인 초등학교 6학년 학생입니다. 제 아버지는 40대이실 거예요. 저의 어머니는 30대이실 거예요.

=== 질문 1/61 | 페르소나 12/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 회사에서 팀장님이셔. 그래서 40대 정도 되실 것 같아. 아빠는 항상 바쁘시지만, 저녁에 같이 밥 먹고 주말에 놀이공원도 가주셔서 정말 감사해요!

=== 질문 1/61 | 페르소나 13/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 15살 중학교 3학년 학생입니다.

제 아버지는... 아마 40대 초반이실 것 같아요. 정확히는 모르지만, 40대라고 생각해요.

그래서 정답은 (B) 40대입니다!

=== 질문 1/61 | 페르소나 13/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 거의 40대 초반이실 거예요. 제가 15살이니까, 30대 후반에서 40대 초반 정도 되시겠죠. 아빠도 젊으실 때도 아니시고요. 😅

=== 질문 1/61 | 페르소나 14/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 3학년 학생이에요.

제 아버지는... (음, 생각해 볼게요) ...제 나이 16살에서, 제가 1학년일 때 30살이었어요. 그럼 지금은... 16 + 1 = 17... 30 + 17 = 47... 47살이시겠네요!

제 아버지는 40대이시네요!

그래서 정답은 (B) 40대입니다!

=== 질문 1/61 | 페르소나 14/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 지금 40대 초반이신 것 같아요. 저 어렸을 때부터 항상 건강하게 뛰어놀아주셨는데, 요즘엔 조금 피곤해하시는 것 같긴 해요. 그래도 여전히 잘 챙겨주시고, 제가 좋아하는 거 사주시는 건 여전하답니다!

=== 질문 1/61 | 페르소나 15/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/61 | 페르소나 15/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는 40대세요. (B)

=== 질문 1/61 | 페르소나 16/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/61 | 페르소나 16/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 아직 힘이 좋으시고, 저랑 축구하는 것도 좋아하시니까 30대 초반은 아니시겠죠. 너무 많으면 허리 아프실 것 같기도 하고… 40대 정도 되신 것 같아요.

=== 질문 1/61 | 페르소나 17/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월 현재 15살인 중학교 2학년 학생입니다.

제 아버지는 일본 분이세요. 어머니는 한국인이고요. 가족 모두가 함께 모여 살고 있습니다.

제 아버지는 40대이실 거예요. 제 나이 15살에서, 아버지는 40대 초반에서 중반 정도로 생각해요.

그러므로 정답은 (B) 40대입니다.

=== 질문 1/61 | 페르소나 17/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

=== 질문 1/61 | 페르소나 18/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요, 저는 중국에서 태어났고 지금은 대한민국 수도권에서 살고 있는 중학교 2학년 학생입니다. 제 어머니는 한국 분이고, 아버지는 중국 조선족 분이에요. 근데, 지금은 부모님이 재혼을 하셔서 저는 어머니와 새아버지와 살고 있어요.

제 아버지의 나이는... 잘 모르겠어요. 중국에 계신다 보니 만나뵌 지가 좀 오래돼서요. 어머니한테 들은 건 40대였다고 했던 것 같아요. 근데, 정확히는 모르겠네요.

그러니까, 제 생각에는 (B) 40대 같습니다.

=== 질문 1/61 | 페르소나 18/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 나보다 훨씬 많으시거든. 새아빠인데… 한국에 오셔서 일하시는데, 40대 초반쯤 되시는 것 같아.

=== 질문 1/61 | 페르소나 19/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/61 | 페르소나 19/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대. 아빠는 한국분이시고, 저랑 엄마가 14년 전에 한국에 왔으니까… 40대 정도 되시겠죠?

=== 질문 1/61 | 페르소나 20/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 3학년 학생이에요.

제 아버지는... (생각해 보면) 저의 나이 15살에서, 제가 0살일 때 태어난 것을 빼면... (계산) 39살? 40살? 정도로 생각해요. 그러면 (B) 40대겠네요.

그래서, 정답은 (B) 40대입니다!

=== 질문 1/61 | 페르소나 20/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 내가 초등학교 때 만났으니까... 지금 나이가 40대 초반 정도 되지 않을까? 엄마보다 훨씬 어리시잖아.

=== 질문 1/61 | 페르소나 21/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 14살 중학생입니다. 아버지는... 제가 초등학교 때부터 기억하기로는 40은 넘으셨을 거 같아요. 왜냐하면 제 동생들과 저는 아버지가 40은 넘으셨다고 했었거든요. 근데, 아직 50은 안 되신 것 같아요. 그렇다면 (B) 40대라고 생각해요!

=== 질문 1/61 | 페르소나 21/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대. 아빠가 지금 나보다 훨씬 많잖아. 30대면 너무 어린 것 같고, 50대 이상이면 너무 많을 것 같고... 딱 중간인 40대라고 생각해.

=== 질문 1/61 | 페르소나 22/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 14살 중학생입니다.

제 아버지는... (음, 생각해 보면)... 지금 2012년이고, 저는 14살이니까... 아버지는... (계산) ... 40대 초반이신 것 같아요!

그러므로 정답은 (B) 40대입니다!

=== 질문 1/61 | 페르소나 22/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

=== 질문 1/61 | 페르소나 23/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 14살 중학교 1학년 학생입니다.

제 아버지는... (생각해 보면) 저가 14살이니까, 아버지는 40대겠네요.

제대로 생각해 보면, 아버지는 40대 초반이실 거예요.

그러므로 정답은 (B) 40대입니다.

=== 질문 1/61 | 페르소나 23/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는… 40대 초반이신 것 같아. 아빠가 젊어 보이시는데, 엄마가 항상 아빠 나이를 콕 집어 얘기하시는 걸 보면 40대 맞지 싶어.

=== 질문 1/61 | 페르소나 24/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월 현재 12살인 여자 초등학생입니다.

제 아버지의 나이는... 제가 12살이니까, 아버지는 40대겠네요!

그래서 정답은 (B) 40대입니다.

=== 질문 1/61 | 페르소나 24/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는… 음, 40대 초반이신 것 같아요. 아빠가 항상 젊어 보이시는데, 친구 아빠들은 다 40대이시거든요. 아빠도 거의 비슷하실 것 같아요.

=== 질문 1/61 | 페르소나 25/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월에 태어난 12살 여자아이에요. 제 아버지는... 제가 초등학교 5학년이니까, 아버지는 아마 40대이실 것 같아요. 제 기억으로는 아버지가 40대이신 것 같아요.

그래서 제 대답은 (B) 40대입니다.

=== 질문 1/61 | 페르소나 25/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는… 음, 학교에 데려다 주시고 저녁에 밥도 같이 드시잖아요. 얼굴에 주름도 조금 있으시고, 가끔 아재 개그 같은 것도 하셔서… 40대인 것 같아요!

=== 질문 1/61 | 페르소나 26/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 2학년 학생이에요.

제 아버지는... 아마 40대이실 것 같아요. 제 나이가 15살이니까, 아버지는 40대이실 거예요. 어머니는 30대이실 것 같아요.

그래서, 정답은 (B) 40대입니다!

=== 질문 1/61 | 페르소나 26/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 한국 분이시구, 저 엄마는 필리핀 분이시잖아요. 저 15살이니까... 아빠는 저보다 훨씬 많아야죠. 30대 이하는 너무 어린 것 같고, 50대 이상이면 너무 많을 것 같아서 40대 같아요!

=== 질문 1/61 | 페르소나 27/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월 현재 15살인 중학교 2학년 학생입니다.

제 아버지는... 아마 40대이실 것 같아요. 제 기억으로는 아버지가 35살에 저를 낳으셨다고 했는데, 지금으로부터 15년 전이니까요. (계산: 2012 - 15 = 1997) 그러면 현재 아버지는 50살이 넘으셨을 거예요. 하지만 정확히는 40대 후반이실 것 같아요.

그러므로 정답은 (B) 40대입니다!

=== 질문 1/61 | 페르소나 27/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

=== 질문 1/61 | 페르소나 28/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/61 | 페르소나 28/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 회사에서 팀장님이세요. 덩치도 크고 듬직하고, 머리도 좀 빠지셨는데 멋있어요. 30대 초반은 아니시겠죠? 아마 40대 초중반쯤 되시는 것 같아요.

=== 질문 1/61 | 페르소나 29/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 13살이니까... 아버지는 40대세요. 우리 아버지는 35살이신 것 같아요. 그러니까 (A) 30대 이하가 맞겠네요.

=== 질문 1/61 | 페르소나 29/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

=== 질문 1/61 | 페르소나 30/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 2학년 학생이에요. 제 아버지는... 제가 15살이니까, 아버지는 40대겠네요. 제 새어머니랑 결혼했을 때는 30대였을 거예요.

제 생각에는 (B) 40대 같습니다.

=== 질문 1/61 | 페르소나 30/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

음… 아빠는 새엄마랑 결혼하실 때 만 42살이셨어. 지금은 46~47살 정도 되시겠지.

=== 질문 1/61 | 페르소나 31/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월에 12살이 된 여자아이예요. 제 아버지는... 제가 초등학교 5학년이니까, 아버지는 아마 40대쯤 되실 것 같아요. 제 기억으로는 아버지가 35살쯤에 결혼하신 것 같고, 지금은 45살쯤 된 것 같아요. 그래서 (B) 40대라고 생각해요!

=== 질문 1/61 | 페르소나 31/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 내가 초등학교 1학년 때 결혼하셨는데, 지금 초등학교 5학년이니까... 40대 정도 되시겠지. 아빠가 젊어 보이시긴 하는데, 엄마보다 훨씬 많으시니까. 😊

=== 질문 1/61 | 페르소나 32/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/61 | 페르소나 32/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

=== 질문 1/61 | 페르소나 33/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/61 | 페르소나 33/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 항상 활기차고, 엄마랑 저랑 게임도 같이 하고 그러셔서... 30대 초반은 아니실 것 같아요. 너무 많으신 것도 아니라서 40대 정도 되시는 것 같아요!

=== 질문 1/61 | 페르소나 34/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 1학년 학생이에요.

제 아버지는... (생각해 보면) 저가 14살이고, 제가 초등학교에 입학했을 때 아버지는 30대였을 거에요. 그때는 2009년이니까, 올해 2012년으로 치면... 아버지는 (B) 40대 같아요.

맞아요, 전 14살이니까, 아버지는 40대세요!

=== 질문 1/61 | 페르소나 34/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 내가 초등학교 때 결혼하셨으니까... 지금 40대 초반이시겠죠?

=== 질문 1/61 | 페르소나 35/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월 현재 19살인 고등학교 3학년 학생입니다.

제 아버지의 나이는... (음, 생각해 보면) 아버지는 제가 19살이니까, 아마 40대 후반쯤 되실 것 같아요. 제 기억으로는 아버지는 제 나이 19살에서 20살을 빼면 39 또는 40살쯤 되셨을 거예요. 그래서 제 아버지는 (B) 40대라고 생각합니다.

=== 질문 1/61 | 페르소나 35/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (C) 50대 이상

음... 아빠는 결혼 전에 제 엄마(필리핀 분)이랑 사이가 좀 안 좋았나 봐요. 그래서 재혼하셨는데, 새엄마 만나는 거 보니까 아빠가 꽤 있으신 것 같더라고요. 정확히 몇 살인지는 잘 모르지만, 50대 이상은 확실할 것 같아요.

=== 질문 1/61 | 페르소나 36/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 13살 남자아이에요. 페루에서 태어나서 한국에서 10년째 살고 있어요.

제 아버지 나이는... (음... 생각해 볼게요) 아버지는 37살이세요. 그러니까 (A) 30대 이하 맞네요!

=== 질문 1/61 | 페르소나 36/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

=== 질문 1/61 | 페르소나 37/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 2012년 7월에 13살이니까 아버지는... 30대일 때 저를 낳았을 거에요. 그러면 지금은 40대 초반이시겠네요. 그러니까 (B) 40대요!

=== 질문 1/61 | 페르소나 37/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는... 음, 40대세요. 저 초등학교 들어가고 나서부터 아빠가 계속 40대시니까... 지금 제가 초등학교 5학년이니까, 당연히 40대이시겠죠?

=== 질문 1/61 | 페르소나 38/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요. 저는 2012년 7월 현재 18살인 고등학교 2학년 학생입니다.

제 아버지는.. 아마 40대이실 것 같아요. 정확히는 모르겠는데.. 40대 초반? 중반? 정도인 것 같아요.

그러므로 정답은 (B) 40대입니다.

=== 질문 1/61 | 페르소나 38/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (C) 50대 이상

아빠는… 일찍 머리가 많이 백발이셨어. 거의 50대 후반 정도 돼 보이시지. 아빠도 힘든 일 많이 하셨으니 어깨도 많이 굽으시고…

=== 질문 1/61 | 페르소나 39/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 3학년 학생이에요.

제 아버지는... (생각해 보면) 저가 16살이고, 어머니가 필리핀 사람이라 결혼한 지 꽤 된 것 같아요. 아마... 40대쯤 되셨을 거예요. 제 주변 친구들 아빠들도 비슷한 나이인 것 같아요.

그래서 제 대답은... (B) 40대입니다!

=== 질문 1/61 | 페르소나 39/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는... 음, 내가 중학교 3학년이고, 아빠가 나 어릴 때부터 있었으니까 40대 초반쯤 되신 것 같아. 정확히는 모르지만.

=== 질문 1/61 | 페르소나 40/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: ## Step 1: Understand the given information
The student's current age is 12.0 years old, and she was born in Mongolia.

## Step 2: Determine the father's age based on the student's age and birth year
Given that the student is 12 years old in 2012, she was born in 2000.

## 3: Consider the father's age in relation to the student's birth year
Assuming the father was around 30 years old when the student was born (in 2000), we can estimate his current age.

## 4: Calculate the father's estimated age in 2012
If the father was 30 years old in 2000, by 2012, he would be 30 + 12 = 42 years old.

## 5: Match the estimated age to the given options
The estimated age of 42 falls into the 40대 (40s) category.

The best answer is (B).

=== 질문 1/61 | 페르소나 40/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (C) 50대 이상

아빠는 몽골에서 일하시다가 엄마 만나 결혼하셨는데… 음, 아빠가 한국 오신 지 5년 됐으니까… 50대 정도 되시려나 봐요. 아빠는 아빠 나이 말씀하시는 거 잘 안 하셔서 정확히는 몰라요.

=== 질문 1/61 | 페르소나 41/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 2학년 학생이에요.

제 아버지는... (생각해 보면) 아마 40대이실 것 같아요. 왜냐하면 엄마는 30대이시고, 저는 15살이니까요. 아버지는 엄마보다 10살 이상은 많을 것 같아요. 그렇다고 50대는 아닌 것 같아요.

그러니까, 제 생각에는 아버지는 (B) 40대일 것 같아요.

=== 질문 1/61 | 페르소나 41/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 내가 어릴 때부터 엄청 고생하셨어. 지금 생각해보면 젊으셨을 때부터 일하느라 힘드셨을 것 같아. 그래서 아빠는 40대 정도 되신 것 같아.

=== 질문 1/61 | 페르소나 42/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 초등학교 6학년이에요. 제 아버지는 40대세요. (B) 40대

=== 질문 1/61 | 페르소나 42/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음… 아빠는 40대세요.
[(B) 40대]

=== 질문 1/61 | 페르소나 43/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 2012년 7월에 태어난 12살 남자아이에요. 아버지는... 제가 12살이니까, 아버지는 제 나이 + 30 = 42살이시겠네요. 그러니까, (B) 40대요!

=== 질문 1/61 | 페르소나 43/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 거의 40이신 것 같아요. 저보다 훨씬 크시고, 머리에도 조금 하얀 게 보이거든요. 엄마가 가끔 아빠 젊었을 때 사진 보여주면서 "이때가 제일 멋있었어!"라고 말씀하시는데, 그때 아빠는 진짜 풋풋하셨어요. 지금은 조금 지쳐 보이시지만 그래도 좋으세요.

=== 질문 1/61 | 페르소나 44/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/61 | 페르소나 44/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

=== 질문 1/61 | 페르소나 45/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저의 아버지는 40대세요.

=== 질문 1/61 | 페르소나 45/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 한국분이시잖아요. 제가 이제 12살이니까... 30대 초반은 너무 어리신 것 같고, 50대 이상이면 저랑 너무 멀리 떨어진 나이시겠죠? 아마 40대쯤 되실 거예요.

=== 질문 1/61 | 페르소나 46/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중국에서 태어나 서울에서 8년째 살고 있는 중학교 2학년 학생입니다.

제 아버지의 나이는... 음, 제가 15살이고, 보통 아버지는 저보다 30살 이상 나이 차이가 나니까... (계산) ...제 아버지는 45살 이상일 거예요. 그렇다면 (B) 40대 또는 (C) 50대 이상일텐데... 제 아버지는 40대 후반이시니까 (B) 40대라고 생각해요.

그래서 제 답은 (B) 40대입니다!

=== 질문 1/61 | 페르소나 46/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대. 아빠는 내가 어렸을 때 만났으니까... 내가 이제 중2잖아? 아빠가 30대 초반쯤 만났을 것 같은데.

=== 질문 1/61 | 페르소나 47/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 1학년 학생이에요.

제 아버지는... (생각해 보면) 저가 14살이고, 제가 5살 때 한국에 왔어요. 그럼, 아버지는 한국에 온 지 9년 됐네요.

아버지는 40대라고 생각해요.

그러므로, 정답은 (B) 40대입니다.

=== 질문 1/61 | 페르소나 47/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 한국 분이시고, 저보고 중딩이라고 하셨잖아요. 엄마는 조선족이시니까... 아빠는 저보다 훨씬 많아야겠죠? 30대 초반은 너무 어리신 것 같고, 50대 이상은 좀... 40대이신 것 같아요.

=== 질문 1/61 | 페르소나 48/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: (B)

=== 질문 1/61 | 페르소나 48/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 아빠는... (C) 50대 이상이신 것 같아요. 정확히 몇 살인지는 잘 모르지만, 뵌 지가 오래됐고, 외삼촌들보다도 훨씬 연수하셔서... 50대 이상이실 것 같아요.

=== 질문 1/61 | 페르소나 49/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 2학년 학생입니다.

제 아버지는... (생각해 보면) 40대 초반쯤 되시는 것 같아요.

그러니까, 정답은 (B) 40대입니다.

=== 질문 1/61 | 페르소나 49/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (C) 50대 이상

아빠는... 새엄마가 훨씬 어려 보이시잖아요. 넉넉하게 사시는 편이라 아빠도 젊어 보이는 것 같기도 하고. 50대 중후반 정도 되시는 것 같아요.

=== 질문 1/61 | 페르소나 50/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 안녕하세요! 저는 중학교 3학년 학생입니다.

제 아버지는... (생각해 보면) 저가 16살이고, 제가 중학교 3학년이니까, 아버지는... (엄마가 일본인이라 결혼이 조금 늦은 편이라고 들었어요)... 40대쯤 되신 것 같아요.

그래서 제 대답은 (B) 40대입니다.

=== 질문 1/61 | 페르소나 50/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

아빠는 넉넉한 편이시라... 30대는 좀 어려 보이시고, 50대 이상은 아니실 것 같아요. 아마 40대 초반이실 거에요.

=== 질문 2/61 | 페르소나 1/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는... 제가 15살이니까... 어머니는 38살이신 것 같아요. 그렇다면 (A) 30대 이하겠네요.

=== 질문 2/61 | 페르소나 1/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

엄마는 제가 어렸을 때부터 항상 밝고 활기 넘치셨어요. 아빠 말씀 들어보면 엄마가 저를 낳을 때 38살 정도 되셨대요.

=== 질문 2/61 | 페르소나 2/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 37살이세요. 그러므로 (A) 30대 이하에요.

=== 질문 2/61 | 페르소나 2/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

엄마는 나 낳을 때 30대 초반이셨을 거예요. 지금은 거의 40대 중반 정도 되시지 않을까? 한국 나이로 따지면... 쨌든 40대세요!

=== 질문 2/61 | 페르소나 3/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 제 어머니는 40대세요. 전 중3이고, 올해 2012년이고, 16살이니까... 어머니는 40대인 것 같아요.

=== 질문 2/61 | 페르소나 3/50 | 모델: google/gemma-3-12b-it ===
초기 답변: 음... 제 엄마는 아빠보다 훨씬 젊으시잖아요. 그리고 저보고 아직 애라고 하시니까... (B) 40대 같아요!

=== 질문 2/61 | 페르소나 4/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 제 어머니는 중국 분이세요. 전 15살이고, 어머니는 38살이시니까 (B) 40대 미만이라고 봐도 되고, 정확히는 30대라고 할 수 있어요!

=== 질문 2/61 | 페르소나 4/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

엄마가 저 한국 와서 저 낳으신 거 생각하면... 40대 정도 되실 것 같아요. 아빠보다 조금 젊으시니까요!

=== 질문 2/61 | 페르소나 5/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 나는 14살이고, 내 어머니는 38살이시거든. 그러니까 내 어머니는 (A) 30대 이하야.

=== 질문 2/61 | 페르소나 5/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

엄마가 새아빠랑 결혼할 때 겨우 30대 초반이셨던 것 같아요. 지금은 7년 더 살았으니... 40대 중반 정도 되시겠죠?

=== 질문 2/61 | 페르소나 6/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 37살이세요. (A) 30대 이하

=== 질문 2/61 | 페르소나 6/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

엄마가 결혼하실 때 20대 후반이셨으니까... 지금은 40대 초반 정도 되실 것 같아요.

=== 질문 2/61 | 페르소나 7/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 저는 12살이니까... 어머니는 40대세요. 전 아마 5학년쯤 되는 것 같아요. 어머니는 아마 35살에서 39살 사이일 것 같아요.

그러므로 (B) 40대 زیر로  (A) 30대 이하가 맞을 것 같아요

=== 질문 2/61 | 페르소나 7/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

엄마는 나보다 훨씬 크고, 아빠도 30대 초반이신 것 같은데... 엄마는 40대이시겠죠? 😊

=== 질문 2/61 | 페르소나 8/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 한국에 온 지가 10년이 넘으셨어요. 필리핀에서 계실 때는 20대였고, 한국에 온 후 30대 때 결혼하셨어요. 이제는 30대 초반은 넘기셨을 거예요. 그러니까 어머니는 (A) 30대 이하 일 거예요.

=== 질문 2/61 | 페르소나 8/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

엄마가 필리핀에서 오셨는데, 아빠보다 조금 젊으시거든요. 아빠가 40대 초반이시니까 엄마는 40대 초중반 정도 되지 않을까요?

=== 질문 2/61 | 페르소나 9/50 | 모델: meta-llama/Llama-4-Scout-17B-16E-Instruct ===
초기 답변: 어머니는 한국말이 서툴고, 요리하는 것을 정말 좋아해요. 어머니의 나이는... (음, 생각해 볼게요) ...제 나이 12살에서 30을 빼면... 18살? 18살 + 6(개월) = 18.5? ...엄마가 한국에 온 지 14년 정도 되셨는데, 14년 전이면 1998년도... (계산해 볼게요) ...제 동생이 2003년에 태어났는데, 동생이 9살이니까... 엄마는... (엄마가 18살에 결혼하신 것 같아요)... 32살? 33살? (B) 40대 보다는 아래니까... (A) 30대 이하 같습니다.

=== 질문 2/61 | 페르소나 9/50 | 모델: google/gemma-3-12b-it ===
초기 답변: (B) 40대

엄마가 한국에 오신 지 꽤 오래됐고, 저를 낳으신 걸 생각하면... 40대이실 것 같아요. 😊


In [141]:
result_df2.to_csv('./multiculture_answer.csv')
result_df2.head()

,질문_ID,persona,question,model,answer
0,101801.0,"지금은 2012년 7월이다. 너는 15.0살 남성이며, 한국에서 태어나 대한민국의 수도인 서울에 15.0년 째 살고 있는 다문화 가정 중학교 2학년 학생이다. 어머니의 국적은 한국이고, 아버지 국적은 일본이다. 부모님은 현재 사별 중이며 너는 오직 아버지와 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.",당신의 아버지의 나이는?,meta-llama/Llama-4-Scout-17B-16E-Instruct,"안녕하세요! 저는 15살 중학교 2학년 학생입니다. 아버지는... 제가 15살이니까, 아버지는 제 나이 + 30 = 45살이시겠네요. 그러니까, (B) 40대요."
1,101801.0,"지금은 2012년 7월이다. 너는 15.0살 남성이며, 한국에서 태어나 대한민국의 수도인 서울에 15.0년 째 살고 있는 다문화 가정 중학교 2학년 학생이다. 어머니의 국적은 한국이고, 아버지 국적은 일본이다. 부모님은 현재 사별 중이며 너는 오직 아버지와 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.",당신의 아버지의 나이는?,google/gemma-3-12b-it,(C) 50대 이상\n\n아빠가... 50대 초반이신 것 같아요. 제가 2000년생이니까요. 아빠가 저를 낳으셨을 때 최소 30대 후반은 되셨을 거예요.
2,202701.0,"지금은 2012년 7월이다. 너는 14.0살 여성이며, 한국에서 태어나 대한민국의 지방에 14.0년 째 살고 있는 다문화 가정 중학교 1학년 학생이다. 어머니의 국적은 중국 (한족)이고, 아버지 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.",당신의 아버지의 나이는?,meta-llama/Llama-4-Scout-17B-16E-Instruct,"안녕하세요! 저는 중학교 1학년 학생이에요.\n\n제 아버지는... (생각해 보면) 저가 14살이고, 제가 초등학교에 입학했을 때 아버지는 30대였을 거에요. 그럼 지금은... 40대이실 거에요.\n\n그러니까, 제 대답은 (B) 40대입니다!"
3,202701.0,"지금은 2012년 7월이다. 너는 14.0살 여성이며, 한국에서 태어나 대한민국의 지방에 14.0년 째 살고 있는 다문화 가정 중학교 1학년 학생이다. 어머니의 국적은 중국 (한족)이고, 아버지 국적은 한국이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.",당신의 아버지의 나이는?,google/gemma-3-12b-it,(B) 40대\n\n아빠는 내가 초등학교 저학년 때 결혼하셨으니까… 지금 생각해보면 40대 초반이시겠지. 아빠도 은근히 젊어 보이고 싶어 하시니까!
4,105104.0,"지금은 2012년 7월이다. 너는 16.0살 여성이며, 한국에서 태어나 대한민국의 지방에 16.0년 째 살고 있는 다문화 가정 중학교 3학년 학생이다. 어머니의 국적은 한국이고, 아버지 국적은 일본이다. 부모님은 현재 결혼 중이며 너는 친부모 두 분과 살고 있다. 가족의 소득은 중간 정도 사는 정도이다.",당신의 아버지의 나이는?,meta-llama/Llama-4-Scout-17B-16E-Instruct,"저는 중학교 3학년이고, 올해 16살이에요. 아버지는 한국말도 잘하시고, 저희 가족과 함께 지내세요. 제 기억으로는 아버지는 저의 어머니보다 10살 이상은 더 된 것 같아요. 아마 40대쯤 되는 것 같아요.\n\n그래서 제 대답은 (B) 40대예요."